services:
  caption:
    build: .
    ports:
      - "5000:5000"
    # volumes: # Voluming takes significantly longer than running from copied files in container
    #   - ./:/app # Volume from WSL, see README.md
    tty: true # can be false in a production environment; helps see color in container logging
    environment:
      - FLASK_ENV=production
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
